2017-07-17 14:21:56,966 [Thread-8:2384] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:37:21,125 [Thread-5:6172] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:38:24,286 [Thread-6:7472] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:39:26,723 [Thread-2:9156] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:39:50,908 [Thread-9:4236] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:41:01,772 [Thread-15:6296] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 14:57:29,157 [Thread-2:10860] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1437, in _changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 651, in get_form
    % (e, self.__class__.__name__)
FieldError: 'date_publish' cannot be specified for Article model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2017-07-17 14:57:40,377 [Thread-9:6668] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1437, in _changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 651, in get_form
    % (e, self.__class__.__name__)
FieldError: 'date_publish' cannot be specified for Article model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2017-07-17 15:06:43,259 [Thread-8:2780] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 15:10:30,548 [Thread-5:6200] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 15:11:40,523 [Thread-2:3920] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 15:11:45,043 [Thread-4:7780] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-07-17 21:16:05,003 [Thread-10:4872] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\contrib\admin\options.py", line 979, in save_model
    obj.save()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\models\sql\compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Heng\Envs\blog_project\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1048, u"Column 'user_id' cannot be null")
2017-10-13 02:52:00,010 [uWSGIWorker4Core0:-1225532736] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./blog_project/urls.py", line 24, in <module>
    url(r'^staticfiles/(?P<path>.*)$', views.static.serve, {'document_root':settings.MEDIA_ROOT,}),
AttributeError: 'module' object has no attribute 'static'
2017-10-13 02:52:00,584 [uWSGIWorker2Core0:-1225532736] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./blog_project/urls.py", line 24, in <module>
    url(r'^staticfiles/(?P<path>.*)$', views.static.serve, {'document_root':settings.MEDIA_ROOT,}),
AttributeError: 'module' object has no attribute 'static'
2017-10-13 02:52:00,765 [uWSGIWorker1Core0:-1225532736] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./blog_project/urls.py", line 24, in <module>
    url(r'^staticfiles/(?P<path>.*)$', views.static.serve, {'document_root':settings.MEDIA_ROOT,}),
AttributeError: 'module' object has no attribute 'static'
2017-10-13 02:52:24,212 [uWSGIWorker2Core0:-1225532736] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./blog_project/urls.py", line 24, in <module>
    url(r'^staticfiles/(?P<path>.*)$', views.static.serve, {'document_root':settings.MEDIA_ROOT,}),
AttributeError: 'module' object has no attribute 'static'
2017-10-13 02:58:51,329 [uWSGIWorker2Core0:-1225266496] [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./blog_project/urls.py", line 24, in <module>
    url(r'^staticfiles/(?P<path>.*)$', views.static.serve, {'document_root':settings.MEDIA_ROOT,}),
AttributeError: 'module' object has no attribute 'static'
